services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
    depends_on:
      - redis
    ports:
      - '80:80'


